package server_test

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"hearthlane-relay/internal/server"
	"hearthlane-relay/internal/state"
	"hearthlane-relay/internal/store"
)

type env struct {
	ts   *httptest.Server
	path string
	logs *bytes.Buffer
}

func newTestServer(t *testing.T) *env {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "state.json")
	return newTestServerAt(t, path, state.New())
}

func newTestServerAt(t *testing.T, path string, st *state.State) *env {
	t.Helper()
	sts := store.New(path)
	logs := &bytes.Buffer{}
	logger := log.New(logs, "relay: ", 0)
	srv := server.New(st, sts, logger)
	ts := httptest.NewServer(srv.Handler())
	t.Cleanup(ts.Close)
	return &env{ts: ts, path: path, logs: logs}
}

func doRequest(t *testing.T, e *env, method, url string, body any) (*http.Response, []byte) {
	t.Helper()
	var rd io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			t.Fatal(err)
		}
		rd = bytes.NewReader(b)
	}
	req, err := http.NewRequest(method, url, rd)
	if err != nil {
		t.Fatal(err)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatal(err)
	}
	return resp, data
}

func mustDo(t *testing.T, e *env, method, url string, body any) (*http.Response, []byte) {
	t.Helper()
	resp, data := doRequest(t, e, method, url, body)
	if data != nil && (resp.StatusCode < 200 || resp.StatusCode >= 300) {
		t.Fatalf("%s %s: unexpected status %d: %s", method, url, resp.StatusCode, data)
	}
	return resp, data
}

func locationURL(e *env, deviceID string) string {
	return e.ts.URL + "/devices/" + deviceID + "/location"
}

func nicknameURL(e *env, deviceID string) string {
	return e.ts.URL + "/devices/" + deviceID + "/nickname"
}

func TestPublishLocationAndGet(t *testing.T) {
	e := newTestServer(t)
	body := map[string]any{
		"latitude":          -23.55,
		"longitude":         -46.63,
		"accuracy":          50,
		"provider":          "network",
		"recordedAtEpochMs": 1234567890000,
	}
	mustDo(t, e, "PUT", locationURL(e, "hearthlane-ab12cd34"), body)

	resp, data := mustDo(t, e, "GET", locationURL(e, "hearthlane-ab12cd34"), nil)
	if ct := resp.Header.Get("Content-Type"); !strings.Contains(ct, "application/json") {
		t.Fatalf("unexpected content type %q", ct)
	}
	var got struct {
		DeviceID           string   `json:"deviceId"`
		Latitude           float64  `json:"latitude"`
		Longitude          float64  `json:"longitude"`
		Accuracy           *float64 `json:"accuracy"`
		Provider           *string  `json:"provider"`
		RecordedAtEpochMs  *int64   `json:"recordedAtEpochMs"`
		PublishedAtEpochMs int64    `json:"publishedAtEpochMs"`
	}
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatal(err)
	}
	if got.DeviceID != "hearthlane-ab12cd34" || got.Latitude != -23.55 || got.Longitude != -46.63 {
		t.Fatalf("unexpected body: %+v", got)
	}
	if got.Accuracy == nil || *got.Accuracy != 50 {
		t.Fatalf("missing accuracy: %+v", got.Accuracy)
	}
	if got.Provider == nil || *got.Provider != "network" {
		t.Fatalf("missing provider: %+v", got.Provider)
	}
	if got.RecordedAtEpochMs == nil || *got.RecordedAtEpochMs != 1234567890000 {
		t.Fatalf("missing recordedAtEpochMs: %+v", got.RecordedAtEpochMs)
	}
	if got.PublishedAtEpochMs <= 0 {
		t.Fatalf("publishedAtEpochMs must be generated by the relay, got %d", got.PublishedAtEpochMs)
	}
}

func TestPublishReplacesPrevious(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2})
	_, d1 := mustDo(t, e, "GET", locationURL(e, "d1"), nil)
	time.Sleep(5 * time.Millisecond)
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 3, "longitude": 4})
	_, d2 := mustDo(t, e, "GET", locationURL(e, "d1"), nil)

	var loc1, loc2 struct {
		Latitude           float64 `json:"latitude"`
		Longitude          float64 `json:"longitude"`
		PublishedAtEpochMs int64   `json:"publishedAtEpochMs"`
	}
	if err := json.Unmarshal(d1, &loc1); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(d2, &loc2); err != nil {
		t.Fatal(err)
	}
	if loc2.Latitude != 3 || loc2.Longitude != 4 {
		t.Fatalf("location not replaced: %+v", loc2)
	}
	if loc2.PublishedAtEpochMs < loc1.PublishedAtEpochMs {
		t.Fatalf("publishedAtEpochMs must not decrease: %d -> %d", loc1.PublishedAtEpochMs, loc2.PublishedAtEpochMs)
	}
}

func TestPublishedAtEpochMsIgnoredFromClient(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{
		"latitude": 1, "longitude": 2, "publishedAtEpochMs": 42, "unexpectedField": "ignored",
	})
	_, data := mustDo(t, e, "GET", locationURL(e, "d1"), nil)
	var loc struct {
		PublishedAtEpochMs int64 `json:"publishedAtEpochMs"`
	}
	if err := json.Unmarshal(data, &loc); err != nil {
		t.Fatal(err)
	}
	if loc.PublishedAtEpochMs < time.Now().Add(-time.Minute).UnixMilli() {
		t.Fatalf("client-controlled publishedAtEpochMs leaked through: %d", loc.PublishedAtEpochMs)
	}
}

func TestGetLocationNotFound(t *testing.T) {
	e := newTestServer(t)
	resp, data := doRequest(t, e, "GET", locationURL(e, "unknown"), nil)
	if resp.StatusCode != http.StatusNotFound {
		t.Fatalf("expected 404, got %d: %s", resp.StatusCode, data)
	}
}

func TestGetLocation404ForDeviceWithoutLocation(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": "x"})
	resp, _ := doRequest(t, e, "GET", locationURL(e, "d1"), nil)
	if resp.StatusCode != http.StatusNotFound {
		t.Fatalf("expected 404 for device without location, got %d", resp.StatusCode)
	}
}

func TestListDevices(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", locationURL(e, "d2"), map[string]any{"latitude": 2, "longitude": 3, "accuracy": 5})
	mustDo(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": "Meu celular"})
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2})

	resp, data := doRequest(t, e, "GET", e.ts.URL+"/devices", nil)
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
	if strings.Contains(string(data), `"latitude"`) || strings.Contains(string(data), `"longitude"`) {
		t.Fatalf("device list must not include coordinates: %s", data)
	}
	var out struct {
		Devices []struct {
			DeviceID           string   `json:"deviceId"`
			Nickname           string   `json:"nickname"`
			HasLocation        bool     `json:"hasLocation"`
			PublishedAtEpochMs *int64   `json:"publishedAtEpochMs"`
			Accuracy           *float64 `json:"accuracy"`
		} `json:"devices"`
	}
	if err := json.Unmarshal(data, &out); err != nil {
		t.Fatal(err)
	}
	if len(out.Devices) != 2 {
		t.Fatalf("expected 2 devices, got %d", len(out.Devices))
	}
	if out.Devices[0].DeviceID != "d1" || out.Devices[1].DeviceID != "d2" {
		t.Fatalf("expected sorted devices, got %+v", out.Devices)
	}
	if out.Devices[0].Nickname != "Meu celular" || out.Devices[0].HasLocation != true {
		t.Fatalf("unexpected d1 summary: %+v", out.Devices[0])
	}
	if out.Devices[1].HasLocation != true || out.Devices[1].PublishedAtEpochMs == nil {
		t.Fatalf("unexpected d2 summary: %+v", out.Devices[1])
	}
	if out.Devices[1].Accuracy == nil || *out.Devices[1].Accuracy != 5 {
		t.Fatalf("expected accuracy in list: %+v", out.Devices[1].Accuracy)
	}
}

func TestListDevicesEmpty(t *testing.T) {
	e := newTestServer(t)
	_, data := mustDo(t, e, "GET", e.ts.URL+"/devices", nil)
	var out struct {
		Devices []any `json:"devices"`
	}
	if err := json.Unmarshal(data, &out); err != nil {
		t.Fatal(err)
	}
	if len(out.Devices) != 0 {
		t.Fatalf("expected empty list, got %s", data)
	}
}

func TestNicknameSetChangeAndClear(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": "Meu celular"})

	_, data := mustDo(t, e, "GET", e.ts.URL+"/devices", nil)
	if !strings.Contains(string(data), "Meu celular") {
		t.Fatalf("nickname not listed: %s", data)
	}

	mustDo(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": "Celular da mae"})
	_, data = mustDo(t, e, "GET", e.ts.URL+"/devices", nil)
	if !strings.Contains(string(data), "Celular da mae") || strings.Contains(string(data), "Meu celular") {
		t.Fatalf("nickname change failed: %s", data)
	}

	mustDo(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": ""})
	_, data = mustDo(t, e, "GET", e.ts.URL+"/devices", nil)
	if strings.Contains(string(data), "Celular da mae") {
		t.Fatalf("nickname not cleared: %s", data)
	}
}

func TestClearNicknameWithLocationKeepsDevice(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2})
	mustDo(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": "x"})
	mustDo(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": ""})
	_, data := mustDo(t, e, "GET", e.ts.URL+"/devices", nil)
	if !strings.Contains(string(data), `"deviceId":"d1"`) {
		t.Fatalf("device with location must remain after clearing nickname: %s", data)
	}
}

func TestPublishDoesNotClearNickname(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": "Meu celular"})
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2})
	_, data := mustDo(t, e, "GET", e.ts.URL+"/devices", nil)
	if !strings.Contains(string(data), "Meu celular") {
		t.Fatalf("nickname lost after publish: %s", data)
	}
}

func TestNicknameDoesNotAffectLocation(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2})
	mustDo(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": "novo"})
	_, data := mustDo(t, e, "GET", locationURL(e, "d1"), nil)
	var loc struct {
		Latitude  float64 `json:"latitude"`
		Longitude float64 `json:"longitude"`
	}
	if err := json.Unmarshal(data, &loc); err != nil {
		t.Fatal(err)
	}
	if loc.Latitude != 1 || loc.Longitude != 2 {
		t.Fatalf("location changed by nickname: %+v", loc)
	}
}

func TestEndpointsWorkWithoutAuthorization(t *testing.T) {
	e := newTestServer(t)

	resp, _ := doRequest(t, e, "GET", e.ts.URL+"/devices", nil)
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("GET /devices without Authorization: expected 200, got %d", resp.StatusCode)
	}

	resp, _ = doRequest(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2})
	if resp.StatusCode != http.StatusNoContent {
		t.Fatalf("PUT /devices/{id}/location without Authorization: expected 204, got %d", resp.StatusCode)
	}

	resp, _ = doRequest(t, e, "GET", locationURL(e, "d1"), nil)
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("GET /devices/{id}/location without Authorization: expected 200, got %d", resp.StatusCode)
	}

	resp, _ = doRequest(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": "sem auth"})
	if resp.StatusCode != http.StatusNoContent {
		t.Fatalf("PUT /devices/{id}/nickname without Authorization: expected 204, got %d", resp.StatusCode)
	}
}

func TestAuthorizationHeaderIgnored(t *testing.T) {
	e := newTestServer(t)
	for _, scheme := range []string{
		"Bearer whatever",
		"Basic dG9rZW4=",
		"Token some-token",
		"",
	} {
		req, _ := http.NewRequest("GET", e.ts.URL+"/devices", nil)
		if scheme != "" {
			req.Header.Set("Authorization", scheme)
		}
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatal(err)
		}
		resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			t.Fatalf("Authorization %q: expected 200, got %d", scheme, resp.StatusCode)
		}
	}
}

func TestNoV1Prefix(t *testing.T) {
	e := newTestServer(t)
	for _, tc := range []struct {
		method string
		url    string
	}{
		{"GET", e.ts.URL + "/v1/devices"},
		{"GET", e.ts.URL + "/v1/devices/d1/location"},
		{"PUT", e.ts.URL + "/v1/devices/d1/location"},
	} {
		resp, _ := doRequest(t, e, tc.method, tc.url, map[string]any{"latitude": 1, "longitude": 2})
		if resp.StatusCode != http.StatusNotFound {
			t.Fatalf("%s %s: expected 404 (no /v1 prefix), got %d", tc.method, tc.url, resp.StatusCode)
		}
	}
}

func TestMethodNotAllowed(t *testing.T) {
	e := newTestServer(t)
	for _, tc := range []struct {
		method string
		url    string
		body   any
	}{
		{"POST", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2}},
		{"GET", nicknameURL(e, "d1"), nil},
		{"DELETE", locationURL(e, "d1"), nil},
	} {
		resp, _ := doRequest(t, e, tc.method, tc.url, tc.body)
		if resp.StatusCode != http.StatusMethodNotAllowed {
			t.Fatalf("%s %s: expected 405, got %d", tc.method, tc.url, resp.StatusCode)
		}
	}
}

func TestUnknownPathNotFound(t *testing.T) {
	e := newTestServer(t)
	resp, _ := doRequest(t, e, "GET", e.ts.URL+"/unknown", nil)
	if resp.StatusCode != http.StatusNotFound {
		t.Fatalf("expected 404, got %d", resp.StatusCode)
	}
}

func TestInvalidDeviceID(t *testing.T) {
	e := newTestServer(t)
	long := strings.Repeat("a", 129)
	for _, tc := range []struct {
		name string
		url  string
	}{
		{"slash", e.ts.URL + "/devices/a%2Fb/location"},
		{"too long", e.ts.URL + "/devices/" + long + "/location"},
		{"slash nickname", e.ts.URL + "/devices/a%2Fb/nickname"},
	} {
		resp, data := doRequest(t, e, "PUT", tc.url, map[string]any{"latitude": 1, "longitude": 2})
		if resp.StatusCode != http.StatusBadRequest {
			t.Fatalf("%s: expected 400, got %d: %s", tc.name, resp.StatusCode, data)
		}
	}
}

func TestInvalidPayloads(t *testing.T) {
	e := newTestServer(t)
	raw := func(body string) *http.Response {
		req, _ := http.NewRequest("PUT", locationURL(e, "d1"), strings.NewReader(body))
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatal(err)
		}
		resp.Body.Close()
		return resp
	}
	cases := []string{
		`{}`,
		`{"latitude":0}`,
		`{"longitude":0}`,
		`{"latitude":91,"longitude":0}`,
		`{"latitude":-91,"longitude":0}`,
		`{"latitude":0,"longitude":181}`,
		`{"latitude":0,"longitude":-181}`,
		`{"latitude":0,"longitude":0,"accuracy":-1}`,
		`{"latitude":0,"longitude":0,"recordedAtEpochMs":-1}`,
		`{"latitude":"x","longitude":0}`,
		`not json at all`,
		``,
	}
	for _, c := range cases {
		if resp := raw(c); resp.StatusCode != http.StatusBadRequest {
			t.Fatalf("body %q: expected 400, got %d", c, resp.StatusCode)
		}
	}
}

func TestInvalidNicknameBodies(t *testing.T) {
	e := newTestServer(t)
	for _, tc := range []struct {
		body string
	}{
		{`{}`},
		{`{"nickname":42}`},
		{`{"nickname":"` + strings.Repeat("x", 201) + `"}`},
		{``},
	} {
		req, _ := http.NewRequest("PUT", nicknameURL(e, "d1"), strings.NewReader(tc.body))
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatal(err)
		}
		resp.Body.Close()
		if resp.StatusCode != http.StatusBadRequest {
			t.Fatalf("body %q: expected 400, got %d", tc.body, resp.StatusCode)
		}
	}
}

func TestPersistenceAfterPublish(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2, "accuracy": 9})
	data, err := os.ReadFile(e.path)
	if err != nil {
		t.Fatal(err)
	}
	var file struct {
		Devices map[string]struct {
			Location struct {
				Latitude           float64 `json:"latitude"`
				Longitude          float64 `json:"longitude"`
				PublishedAtEpochMs int64   `json:"publishedAtEpochMs"`
			} `json:"location"`
		} `json:"devices"`
	}
	if err := json.Unmarshal(data, &file); err != nil {
		t.Fatalf("state file is not valid JSON: %v", err)
	}
	d, ok := file.Devices["d1"]
	if !ok || d.Location.Latitude != 1 || d.Location.Longitude != 2 {
		t.Fatalf("state file missing published location: %+v", file)
	}
	if d.Location.PublishedAtEpochMs <= 0 {
		t.Fatalf("state file location missing publishedAtEpochMs: %+v", file)
	}
}

func TestRestoreAfterRestart(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": -23.55, "longitude": -46.63})
	mustDo(t, e, "PUT", nicknameURL(e, "d2"), map[string]any{"nickname": "Tablet"})

	sts := store.New(e.path)
	st, err := sts.Load()
	if err != nil {
		t.Fatal(err)
	}
	if st.DeviceCount() != 2 {
		t.Fatalf("expected 2 devices after restart, got %d", st.DeviceCount())
	}
	restarted := newTestServerAt(t, e.path, st)
	_, data := mustDo(t, restarted, "GET", locationURL(restarted, "d1"), nil)
	var loc struct {
		Latitude  float64 `json:"latitude"`
		Longitude float64 `json:"longitude"`
	}
	if err := json.Unmarshal(data, &loc); err != nil {
		t.Fatal(err)
	}
	if loc.Latitude != -23.55 || loc.Longitude != -46.63 {
		t.Fatalf("location not restored after restart: %+v", loc)
	}
	_, data = mustDo(t, restarted, "GET", restarted.ts.URL+"/devices", nil)
	if !strings.Contains(string(data), "Tablet") {
		t.Fatalf("nickname not restored after restart: %s", data)
	}
}

func TestCorruptFileStillServedFromMemory(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2})
	if err := os.WriteFile(e.path, []byte("corrupted-on-disk"), 0o600); err != nil {
		t.Fatal(err)
	}
	_, data := mustDo(t, e, "GET", locationURL(e, "d1"), nil)
	var loc struct {
		Latitude  float64 `json:"latitude"`
		Longitude float64 `json:"longitude"`
	}
	if err := json.Unmarshal(data, &loc); err != nil {
		t.Fatal(err)
	}
	if loc.Latitude != 1 || loc.Longitude != 2 {
		t.Fatalf("GET must be served from memory, got %+v", loc)
	}
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 3, "longitude": 4})
	raw, err := os.ReadFile(e.path)
	if err != nil {
		t.Fatal(err)
	}
	if !json.Valid(raw) {
		t.Fatalf("state file must be valid after rewrite: %s", raw)
	}
}

func TestStateFileOnlyCurrentLocation(t *testing.T) {
	e := newTestServer(t)
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2})
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 3, "longitude": 4})
	mustDo(t, e, "PUT", nicknameURL(e, "d1"), map[string]any{"nickname": "x"})
	raw, err := os.ReadFile(e.path)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Count(string(raw), `"latitude"`) != 1 || strings.Count(string(raw), `"longitude"`) != 1 {
		t.Fatalf("state file must contain only the last location: %s", raw)
	}
}

func TestConcurrentGetAndPut(t *testing.T) {
	e := newTestServer(t)
	const devices = 10
	var wg sync.WaitGroup
	for i := 0; i < 20; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			for j := 0; j < 10; j++ {
				id := fmt.Sprintf("dev-%d", (i+j)%devices)
				req, _ := http.NewRequest("PUT", locationURL(e, id), jsonBody(t, map[string]any{"latitude": j, "longitude": j}))
				resp, err := http.DefaultClient.Do(req)
				if err != nil {
					t.Error(err)
					return
				}
				_, _ = io.Copy(io.Discard, resp.Body)
				resp.Body.Close()
			}
		}(i)
	}
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			for j := 0; j < 20; j++ {
				req, _ := http.NewRequest("GET", locationURL(e, fmt.Sprintf("dev-%d", j%devices)), nil)
				resp, err := http.DefaultClient.Do(req)
				if err != nil {
					t.Error(err)
					return
				}
				_, _ = io.Copy(io.Discard, resp.Body)
				resp.Body.Close()
			}
		}(i)
	}
	wg.Wait()

	raw, err := os.ReadFile(e.path)
	if err != nil {
		t.Fatal(err)
	}
	if !json.Valid(raw) {
		t.Fatalf("state file corrupted by concurrent writes: %s", raw)
	}
	var file struct {
		Devices map[string]any `json:"devices"`
	}
	if err := json.Unmarshal(raw, &file); err != nil {
		t.Fatal(err)
	}
	if len(file.Devices) != devices {
		t.Fatalf("expected %d devices, got %d", devices, len(file.Devices))
	}
}

func jsonBody(t *testing.T, v any) io.Reader {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return bytes.NewReader(b)
}

func TestNoSensitiveDataInLogs(t *testing.T) {
	const lat = "-12.345678"
	const lon = "-45.678901"
	e := newTestServer(t)

	body := map[string]any{"latitude": -12.345678, "longitude": -45.678901, "accuracy": 12}
	mustDo(t, e, "PUT", locationURL(e, "d1"), body)
	mustDo(t, e, "PUT", locationURL(e, "d2"), map[string]any{"latitude": 0, "longitude": 0})

	req, _ := http.NewRequest("PUT", locationURL(e, "d3"), strings.NewReader(`{"latitude":91,"longitude":0}`))
	req.Header.Set("Authorization", "Bearer super-secret-token-123")
	if resp, err := http.DefaultClient.Do(req); err != nil {
		t.Fatal(err)
	} else {
		resp.Body.Close()
	}

	req, _ = http.NewRequest("GET", e.ts.URL+"/devices", nil)
	req.Header.Set("Authorization", "Bearer wrong")
	if resp, err := http.DefaultClient.Do(req); err != nil {
		t.Fatal(err)
	} else {
		resp.Body.Close()
	}

	logs := e.logs.String()
	for _, secret := range []string{lat, lon, "-12.345678,-45.678901"} {
		if strings.Contains(logs, secret) {
			t.Fatalf("log leak of %q:\n%s", secret, logs)
		}
	}
	for _, auth := range []string{"Bearer", "super-secret-token-123", "wrong"} {
		if strings.Contains(logs, auth) {
			t.Fatalf("Authorization material leaked in logs: %q:\n%s", auth, logs)
		}
	}
	if !strings.Contains(logs, "method=PUT") || !strings.Contains(logs, "status=204") {
		t.Fatalf("expected sanitized operational logs:\n%s", logs)
	}
}

func TestPublishedAtGeneratedByRelay(t *testing.T) {
	e := newTestServer(t)
	before := time.Now().UnixMilli()
	mustDo(t, e, "PUT", locationURL(e, "d1"), map[string]any{"latitude": 1, "longitude": 2})
	_, data := mustDo(t, e, "GET", locationURL(e, "d1"), nil)
	var loc struct {
		PublishedAtEpochMs int64 `json:"publishedAtEpochMs"`
	}
	if err := json.Unmarshal(data, &loc); err != nil {
		t.Fatal(err)
	}
	if loc.PublishedAtEpochMs < before {
		t.Fatalf("publishedAtEpochMs must be generated at acceptance time by the relay, got %d (before %d)", loc.PublishedAtEpochMs, before)
	}
}
